name: Unit Tests - EvalML with Woodwork main branch
on:
  workflow_dispatch:
jobs:
  unit_tests_woodwork_main:
    if: ${{ github.repository_owner == 'alteryx' }}
    name: ${{ matrix.python_version }} unit tests ${{ matrix.libraries }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python_version: ["3.8", "3.9"]
        libraries: ["core"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update apt and install Graphviz
        run: sudo apt update && sudo apt install -y graphviz
      - name: Set up pip
        run: |
          pip config --site set global.progress_bar off
          python -m pip install -U pip
      - name: Install EvalML & Woodwork - test requirements
        run: |
          make installdeps-prophet
          make installdeps-test
          python -m pip uninstall -y woodwork
          python -m pip install https://github.com/alteryx/woodwork/archive/main.zip
      - name: Run unit tests without code coverage
        run: |
          echo "Run unit tests without code coverage for ${{ matrix.python_version }} and ${{ matrix.libraries }}"
          echo "Testing with EvalML version:" `python -c "import evalml; print(evalml.__version__)"`
          pytest evalml/ -n 2 --ignore=evalml/tests/automl_tests/parallel_tests
          pip check
  slack_alert_failure:
    name: Send Slack alert if failure
    needs: unit_tests_woodwork_main
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Send Slack alert if failure
        if: ${{ needs.unit_tests_woodwork_main.result != 'success' }}
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WW_TO_EVALML_WEBHOOK }}
